# Generated by Django 5.0 on 2023-12-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='position',
            name='pos_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
