# Generated by Django 5.0 on 2023-12-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_position_description_position_pos_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='pos_name',
            new_name='title',
        ),
    ]
