# Generated by Django 5.0 on 2024-01-27 14:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Overtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_date', models.DateField(default=datetime.datetime.now)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.DateField(blank=True, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('description', models.TextField(blank=True)),
                ('first_app_status', models.IntegerField(default=0)),
                ('second_app_status', models.IntegerField(default=0)),
                ('third_app_status', models.IntegerField(default=0)),
                ('fourth_app_status', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('approval_position', models.IntegerField(default=1)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approval_ot', to=settings.AUTH_USER_MODEL)),
                ('fourth_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fouth_approval_ot', to=settings.AUTH_USER_MODEL)),
                ('second_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approval_ot', to=settings.AUTH_USER_MODEL)),
                ('third_approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_approval_ot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
