# Generated by Django 5.0 on 2024-01-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_alter_overtime_to_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overtime',
            old_name='description',
            new_name='reason',
        ),
    ]
