# Generated by Django 5.0 on 2024-02-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_rename_description_overtime_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='straight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
