# Generated by Django 5.0 on 2023-12-29 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vac_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
