# Generated by Django 5.0 on 2023-12-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0002_vacation_vac_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='ampm',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
