# Generated by Django 5.0 on 2024-01-13 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0005_employeeleavestat_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='first_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_approval_vacations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacation',
            name='second_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approval_vacations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacation',
            name='third_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_approval_vacations', to=settings.AUTH_USER_MODEL),
        ),
    ]
