# Generated by Django 5.0 on 2024-01-13 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0006_vacation_first_approval_vacation_second_approval_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='fourth_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fouth_approval_vacations', to=settings.AUTH_USER_MODEL),
        ),
    ]
