# Generated by Django 5.0 on 2024-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0007_vacation_fourth_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='first_app_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacation',
            name='fourth_app_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacation',
            name='second_app_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vacation',
            name='third_app_status',
            field=models.IntegerField(default=0),
        ),
    ]
