# Generated by Django 5.0 on 2024-01-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0009_vacation_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacation',
            name='approved',
        ),
        migrations.AddField(
            model_name='vacation',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
