# Generated by Django 5.0 on 2024-01-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0010_remove_vacation_approved_vacation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='approval_position',
            field=models.IntegerField(default=1),
        ),
    ]
