# Generated by Django 5.0 on 2024-02-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0011_vacation_approval_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='first_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
