# Generated by Django 5.0 on 2024-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0012_vacation_first_app_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='fourth_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='second_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vacation',
            name='third_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
