# Generated by Django 4.2.7 on 2024-02-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0013_vacation_fourth_app_date_vacation_second_app_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='sofar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
