# Generated by Django 4.2.7 on 2024-02-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0014_vacation_sofar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavestat',
            name='current_year',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavestat',
            name='daystaken_current',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavestat',
            name='previous_year',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavestat',
            name='total_annual',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
