# Generated by Django 5.0 on 2024-03-02 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0015_alter_employeeleavestat_current_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='leave_stat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vacations.employeeleavestat'),
        ),
    ]
