# Generated by Django 5.0 on 2024-03-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
