# Generated by Django 5.0 on 2023-12-21 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='departrment',
            new_name='department',
        ),
    ]
