# Generated by Django 5.0 on 2023-12-18 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_head_dep'),
        ('departments', '0001_initial'),
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='departrment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department'),
        ),
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='positions.position'),
        ),
    ]
