# Generated by Django 5.0 on 2023-12-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_departrment_account_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pofile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
