# Generated by Django 5.0 on 2023-12-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_pofile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pofile_pic',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/photos/employee'),
        ),
    ]
