# Generated by Django 5.0 on 2023-12-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_financial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
