# Generated by Django 5.0 on 2023-12-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_work_finish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='work_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='work_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
