# Generated by Django 5.0 on 2023-12-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nssf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
