# Generated by Django 5.0 on 2024-01-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_is_haed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_haed',
        ),
        migrations.AddField(
            model_name='account',
            name='is_head',
            field=models.BooleanField(default=False),
        ),
    ]
