# Generated by Django 5.0 on 2024-01-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_account_is_haed_account_is_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_vac_ent',
            field=models.BooleanField(default=False),
        ),
    ]
