# Generated by Django 5.0 on 2024-01-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_is_superadmin_alter_account_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_superadmin',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
