# Generated by Django 4.2.7 on 2024-02-24 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medreps', '0002_medrep_first_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='medrep',
            name='approval_position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='medrep',
            name='first_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medrep',
            name='first_app_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medrep',
            name='fourth_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medrep',
            name='fourth_app_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medrep',
            name='fourth_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fouth_approval_medreps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medrep',
            name='second_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medrep',
            name='second_app_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medrep',
            name='second_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_approval_medreps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medrep',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medrep',
            name='third_app_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medrep',
            name='third_app_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medrep',
            name='third_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_approval_medreps', to=settings.AUTH_USER_MODEL),
        ),
    ]
