# Generated by Django 4.2.7 on 2024-02-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medreps', '0003_medrep_approval_position_medrep_first_app_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medrep',
            name='pdf_attachment',
            field=models.FileField(blank=True, null=True, upload_to='pdf/Reports/'),
        ),
    ]
